In [1]:
import numpy as np 
print("numpy loaded successfully")

numpy loaded successfully


In [4]:
np.array(1)  # Output: array(1, 2, 3)
print(type(np.array(1)))  # Output: <class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [7]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)  # Output: [[1 2 3 4 5]
              #          [6 7 8 9 10]]
print(type(arr))  # Output: <class 'numpy.ndarray'>

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [12]:
print(len(arr) ) # python function Output: 10

2


In [15]:
## attribute 
print(arr.shape) # Output: (10,)
print(arr.ndim) # Output: 1  dimension
print(arr.size) # Output: 10
print(arr.dtype)


(2, 5)
2
10
int64


In [18]:
# methods
print(np.arange(0,10)) # start, stop, step


[0 1 2 3 4 5 6 7 8 9]


<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>
2
(2, 5)
2
10


10

In [21]:
np.random.rand(3,4)

array([[0.94979271, 0.02859193, 0.4682848 , 0.41803463],
       [0.86989467, 0.8436411 , 0.9505534 , 0.12261772],
       [0.06073783, 0.6423317 , 0.07464993, 0.92186123]])

In [23]:
np.random.randint(0,10,10)  # start, stop, size

array([5, 7, 8, 4, 2, 4, 3, 8, 1, 2])

In [25]:
# zeros
np.zeros((2,4,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
# min, max , argmax, argmin
print(arr)
arr.ravel()
arr=arr.flatten()

min(arr)  # py func
np.min(arr)  # np method  max 

# index finding
np.argmax(arr)   # argmin

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


np.int64(9)

In [32]:
# mean std
print(arr)
arr+arr    #3 add

list1=[1,2,3,4,5]
list1+list1     # concat

arr.mean()
arr.std()

[ 1  2  3  4  5  6  7  8  9 10]


np.float64(2.8722813232690143)